CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    is_locked BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE,
    is_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMPTZ,
    violation_count INTEGER DEFAULT 0,
    last_violation_at TIMESTAMPTZ,
    locked_until TIMESTAMPTZ,
    permanent_locked BOOLEAN DEFAULT FALSE,
    auth_version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    family_id VARCHAR(36) NOT NULL,
    replaced_by_hash VARCHAR(64),
    user_agent TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    is_revoked BOOLEAN DEFAULT FALSE,
    revoked_at TIMESTAMPTZ,
    revoked_reason VARCHAR(64),
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_family_revoked
    ON refresh_tokens (family_id, is_revoked);
CREATE INDEX idx_refresh_tokens_user_revoked
    ON refresh_tokens (user_id, is_revoked);

CREATE TABLE user_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    city_code VARCHAR(50),
    city_name VARCHAR(100),
    full_name VARCHAR(100),
    date_of_birth DATE,
    gender VARCHAR(20),
    bio VARCHAR(255),
    occupation VARCHAR(100),
    marital_status VARCHAR(20),
    looking_for VARCHAR(20),
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_profiles_user_id UNIQUE (user_id),
    CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_profiles_gender CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT chk_profiles_marital_status CHECK (marital_status IN ('SINGLE', 'DIVORCED', 'WIDOWED', 'MARRIED')),
    CONSTRAINT chk_profiles_looking_for CHECK (looking_for IN ('LOVE', 'FRIENDS', 'NETWORKING'))
);

CREATE TABLE hobbies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    icon VARCHAR(50),
    category VARCHAR(50),
    CONSTRAINT uk_hobbies_code UNIQUE (code)
);

CREATE TABLE user_hobbies (
    user_id INTEGER NOT NULL,
    hobby_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, hobby_id),
    CONSTRAINT fk_user_hobbies_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_hobbies_hobby FOREIGN KEY (hobby_id) REFERENCES hobbies (id) ON DELETE CASCADE
);

CREATE TABLE media (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_id INTEGER,
    url VARCHAR(255) NOT NULL,
    thumbnail_url VARCHAR(255),
    type VARCHAR(20) NOT NULL,
    size_bytes INTEGER,
    storage_provider VARCHAR(20),
    storage_bucket VARCHAR(100),
    object_key VARCHAR(512),
    content_type VARCHAR(100),
    category VARCHAR(20),
    uploaded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_media_uploader FOREIGN KEY (uploader_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT chk_media_type CHECK (type IN ('IMAGE', 'VIDEO')),
    CONSTRAINT uk_media_storage_object UNIQUE (storage_provider, storage_bucket, object_key)
);

CREATE INDEX idx_media_uploader_type ON media (uploader_id, type);
CREATE INDEX idx_media_uploader_url ON media (uploader_id, url);

CREATE TABLE user_avatars (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    media_id INTEGER NOT NULL,
    is_current BOOLEAN DEFAULT FALSE,
    set_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_avatars_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_avatars_media FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE
);

CREATE TABLE user_covers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    media_id INTEGER NOT NULL,
    is_current BOOLEAN DEFAULT FALSE,
    set_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_covers_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_covers_media FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE
);

CREATE TABLE user_gallery (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    media_id INTEGER NOT NULL,
    display_order INTEGER DEFAULT 0,
    is_verified BOOLEAN DEFAULT FALSE,
    added_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_gallery_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_gallery_media FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_gallery_order ON user_gallery (user_id, display_order);

CREATE TABLE friend_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INTEGER NOT NULL,
    receiver_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMPTZ,
    CONSTRAINT fk_requests_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_requests_receiver FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_requests_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED'))
);

CREATE INDEX idx_friend_requests_status ON friend_requests (receiver_id, status);
CREATE INDEX idx_friend_requests_sender_status ON friend_requests (sender_id, status);

CREATE TABLE friends (
    user_id INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friends_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_friends_friend FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE friend_suggestions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    suggested_user_id INTEGER NOT NULL,
    score NUMERIC(5, 2) DEFAULT 0,
    reason VARCHAR(200),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    CONSTRAINT uk_suggestions_pair UNIQUE (user_id, suggested_user_id),
    CONSTRAINT fk_suggestions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_suggestions_target FOREIGN KEY (suggested_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_suggestions_user_expires ON friend_suggestions (user_id, expires_at);
CREATE INDEX idx_suggestions_score ON friend_suggestions (user_id, score DESC);

CREATE TABLE dismissed_suggestions (
    user_id INTEGER NOT NULL,
    dismissed_user_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, dismissed_user_id),
    CONSTRAINT fk_dismissed_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_dismissed_target FOREIGN KEY (dismissed_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    cover_media_id INTEGER,
    privacy VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_groups_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_groups_cover FOREIGN KEY (cover_media_id) REFERENCES media (id) ON DELETE SET NULL,
    CONSTRAINT chk_groups_privacy CHECK (privacy IN ('PUBLIC', 'PRIVATE'))
);

CREATE TABLE group_members (
    group_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACCEPTED',
    invited_by_id INTEGER,
    violation_count INTEGER DEFAULT 0,
    last_violation_at TIMESTAMPTZ,
    joined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (group_id, user_id),
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_group_members_role CHECK (role IN ('MEMBER', 'MODERATOR', 'ADMIN')),
    CONSTRAINT chk_group_members_status CHECK (status IN ('ACCEPTED', 'REQUESTED', 'PENDING', 'BANNED'))
);

CREATE TABLE posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id INTEGER NOT NULL,
    group_id INTEGER,
    original_post_id INTEGER,
    content TEXT,
    visibility VARCHAR(20) DEFAULT 'PUBLIC',
    status VARCHAR(20) DEFAULT 'APPROVED',
    is_deleted BOOLEAN DEFAULT FALSE,
    comment_count INTEGER DEFAULT 0,
    react_count INTEGER DEFAULT 0,
    share_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    ai_score DOUBLE PRECISION DEFAULT 0,
    ai_status VARCHAR(20) DEFAULT 'NOT_CHECKED',
    ai_reason TEXT,
    checked_at TIMESTAMPTZ,
    approved_by_id INTEGER,
    is_pinned BOOLEAN DEFAULT FALSE,
    pinned_at TIMESTAMPTZ,
    CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_posts_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_posts_original_post FOREIGN KEY (original_post_id) REFERENCES posts (id) ON DELETE SET NULL,
    CONSTRAINT fk_posts_approved_by FOREIGN KEY (approved_by_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT chk_posts_visibility CHECK (visibility IN ('PUBLIC', 'FRIENDS', 'PRIVATE')),
    CONSTRAINT chk_posts_status CHECK (status IN ('APPROVED', 'PENDING', 'REJECTED'))
);

CREATE INDEX idx_posts_created_at ON posts (created_at DESC);
CREATE INDEX idx_posts_status ON posts (status);
CREATE INDEX idx_posts_group_feed ON posts (group_id, status, is_deleted, is_pinned DESC, pinned_at DESC, created_at DESC);
CREATE INDEX idx_posts_personal_feed ON posts (status, is_deleted, created_at DESC) WHERE group_id IS NULL;

CREATE TABLE post_media (
    post_id INTEGER NOT NULL,
    media_id INTEGER NOT NULL,
    display_order INTEGER DEFAULT 0,
    PRIMARY KEY (post_id, media_id),
    CONSTRAINT fk_post_media_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT fk_post_media_media FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL,
    author_id INTEGER NOT NULL,
    parent_id INTEGER,
    content TEXT,
    media_id INTEGER,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_parent FOREIGN KEY (parent_id) REFERENCES comments (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_media FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE SET NULL
);

CREATE INDEX idx_comments_post_created ON comments (post_id, created_at DESC);

CREATE TABLE reactions (
    user_id INTEGER NOT NULL,
    post_id INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, post_id),
    CONSTRAINT fk_reactions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reactions_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT chk_reactions_type CHECK (type IN ('LIKE', 'LOVE', 'HAHA', 'WOW', 'SAD', 'ANGRY'))
);

CREATE INDEX idx_reactions_post ON reactions (post_id);

CREATE TABLE chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    avatar_url VARCHAR(255),
    created_by INTEGER NOT NULL,
    firebase_room_key VARCHAR(100) NOT NULL,
    last_message_at TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_chat_rooms_firebase UNIQUE (firebase_room_key),
    CONSTRAINT fk_chat_rooms_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_chat_rooms_type CHECK (type IN ('DIRECT', 'GROUP'))
);

CREATE INDEX idx_chat_last_message ON chat_rooms (last_message_at DESC);

CREATE TABLE chat_room_members (
    chat_room_id BIGINT NOT NULL,
    user_id INTEGER NOT NULL,
    role VARCHAR(20) DEFAULT 'MEMBER',
    nickname VARCHAR(100),
    joined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,
    last_read_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    client_cleared_at TIMESTAMPTZ,
    PRIMARY KEY (chat_room_id, user_id),
    CONSTRAINT fk_chat_members_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms (id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_chat_members_role CHECK (role IN ('MEMBER', 'ADMIN'))
);

CREATE INDEX idx_chat_members_user ON chat_room_members (user_id, left_at);

CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    actor_id INTEGER,
    type VARCHAR(50) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id INTEGER NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_actor FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_notifications_type CHECK (type IN (
        'FRIEND_REQUEST', 'FRIEND_ACCEPT', 'ROLE_CHANGE',
        'POST_COMMENT', 'COMMENT_REPLY', 'POST_REACTION',
        'POST_APPROVED', 'POST_REJECTED', 'POST_PENDING',
        'GROUP_INVITE', 'GROUP_INVITE_ACCEPTED',
        'GROUP_JOIN_REQUEST', 'GROUP_JOIN_APPROVED', 'GROUP_JOIN_REJECTED',
        'GROUP_MEMBER_JOINED', 'GROUP_MEMBER_LEFT',
        'GROUP_BANNED', 'GROUP_UNBAN', 'GROUP_DELETED',
        'GROUP_OWNER_CHANGE', 'GROUP_ROLE_CHANGED',
        'REPORT_SUBMITTED', 'REPORT_UPDATED',
        'LIKE', 'COMMENT', 'GROUP_KICK', 'GROUP_REJECTED',
        'MESSAGE', 'OTHER'
    ))
);

CREATE INDEX idx_notifications_user_read ON notifications (user_id, is_read);

CREATE TABLE reports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id INTEGER NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id INTEGER NOT NULL,
    reason VARCHAR(255),
    status VARCHAR(20) DEFAULT 'PENDING',
    reviewer_id INTEGER,
    admin_note TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_reviewer FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT chk_reports_target_type CHECK (target_type IN ('USER', 'POST', 'COMMENT', 'GROUP', 'MESSAGE')),
    CONSTRAINT chk_reports_status CHECK (status IN ('PENDING', 'REVIEWING', 'RESOLVED', 'DISMISSED'))
);

CREATE TABLE verification_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    user_id INTEGER NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    user_id INTEGER NOT NULL,
    expiry_date TIMESTAMP,
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_public_keys (
    user_id INTEGER PRIMARY KEY,
    public_key TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_public_keys_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
